Adding seacat auth
TeskaLabs/asab-maestro-library pull request #10
Opened 2023-08-18 13:32 UTC by eliska-n

- private/public ports
- remote control probably needs two we containers because of acme challenge..?
- extra config added to https conf

2023-08-18 14:10 UTC, ateska requested changes

2023-08-18 14:10 UTC, ateska commented on Site/ASAB Maestro/Descriptors/seacat-auth.yaml
> +    SEACAT_AUTH_PROVISIONING: 0
This needs to be commented.

2023-08-18 14:10 UTC, ateska commented on Site/ASAB Maestro/Descriptors/seacat-auth.yaml
> +      host=<mocked>
A comment needs to be here ...

2023-08-18 14:10 UTC, ateska commented
Nice ;-)

2023-08-22 13:52 UTC, eliska-n commented
I recreated mongosh script, so there is no need of any bash script and it inserts seacat auth collections.
I tried to cut the original export from mongo as much as possible, so it human readable and editable.
Most of the collections use string as "_id". However, in `c` collection the id is ObjectId, so I made a specific transformation from string to ObjectId in the script for this collection, because insertOne/insertMany methods cannot work with `{"$_oid": "<actual_id>"}` syntax as other parts of mongo do.

Are there any other collections that require this transformation? Who knows!

2023-08-22 13:53 UTC, eliska-n commented
I don't know how to handle logging properly in the script, I ended up with prints and quiting when needed...

2023-08-23 08:30 UTC, ateska commented on Site/ASAB Maestro/Files/mongo/script/to_upload/c.json
> +	"__password": "$2b$12$gV5pNXpjT70qxAqJ.xfEGObiaIa3znrpML4R55EOsM1RvTyGxNbi.",
Is there a plaintext version of this anywhere?

2023-08-23 08:56 UTC, merged