Draft: Adding general config
TeskaLabs/asab-maestro-library pull request #24
Opened 2023-10-12 11:40 UTC by eliska-n

The schema needs more than one item and I need to investigate what is needed for the UI there... there are so many examples and descriptions, but just one of them is actually rendered.

Also, I need to solve this before adding more configs: http://gitlab.teskalabs.int/asab/asab-config/-/merge_requests/61

Plus discussion on slack about arrays in the configuration. I thought we were already over it :see_no_evil:

2023-10-18 12:59 UTC, ateska requested changes

2023-10-18 12:59 UTC, ateska commented on Site/ASAB Maestro/Descriptors/asab-remote-control.yaml
> +      file: asab-config/General/_schema.json
Why there is "_" in the name of schema?

2023-10-18 18:11 UTC, eliska-n commented
This is structure of the export from asab config - I guess I want to keep this structure.
I just still don't know where to specify the "if_not_exists" option
![image](https://github.com/TeskaLabs/asab-maestro-library/assets/82450969/f8a20c57-6edf-424a-826a-451646d1f175)

2023-10-19 15:59 UTC, ateska approved these changes
Change the name and merge it.

2023-11-10 14:30 UTC, merged