Update datasources.yaml
TeskaLabs/asab-maestro-library pull request #54
Opened 2024-01-16 14:00 UTC by PremyslCerny

2024-01-18 19:52 UTC, ateska requested changes

2024-01-18 19:52 UTC, ateska commented on Site/ASAB Maestro/Files/grafana/provisioning/datasources.yaml
> +- name: InfluxDBTelegraf
We don't have two buckets in Influx.

2024-01-18 19:56 UTC, ateska requested changes

2024-01-18 19:56 UTC, ateska commented on Site/ASAB Maestro/Files/grafana/provisioning/datasources.yaml
> +- name: InfluxDB
Must be aligned with https://ndocs.teskalabs.com/logman.io/metrics/viewing-metrics/ 

... which _mainly_ means that all telemetry is in "InfluxDB" datasource.

Which is wrong too, b/c it names the technology.
But ... I give up that fight here.

2024-01-18 20:18 UTC, ateska commented
Here is a dump of my research:


https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#create-a-data-source

```
{
  "uid": "lmio-influxdb-metrics",
  "orgId": 1,
  "name": "InfluxDB",
  "type": "influxdb",
  "typeLogoUrl": "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg",
  "access": "proxy",
  "url": "http://lmio-XXX:8086",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "withCredentials": false,
  "isDefault": true,
  "jsonData": {
    "dbName": "metrics",
    "httpHeaderName1": "Authorization",
    "httpMode": "POST"
  },
  "secureJsonFields": {
    "httpHeaderValue1": "Token YYY"
  },
  "version": 3,
  "readOnly": false
}
```

2024-01-18 20:24 UTC, PremyslCerny commented
assigning to @eliska-n since she wanted to continue with it

2024-02-14 14:47 UTC, ateska commented
Provisioning is working, TODOs has to be fixed.

2024-02-15 17:40 UTC, eliska-n approved these changes

2024-02-15 17:41 UTC, merged