Set the timeout for ES request handling to 10 mins to avoid "Failed t…
TeskaLabs/asab-maestro-library pull request #68
Opened 2024-02-19 08:15 UTC by PremyslCerny

…o get data from Elasticsearch" message in UI

2024-03-08 15:10 UTC, eliska-n commented
oh, I'm sorry, I completely forgot to follow MRs here. 

I'm fine with that. But... who is able to wait 10 mins for the screen to load? :D such request would be probably interrupted by the user.

2024-03-08 15:11 UTC, eliska-n requested changes

2024-03-08 15:11 UTC, eliska-n commented on Site/ASAB Maestro/Descriptors/elasticsearch.yaml
> +      - proxy_connect_timeout 600;
the syntax is wrong. There should not be the `;` in the end

2024-03-08 15:12 UTC, eliska-n commented
Maestro is on app.logman right now. I can't approve MRs to be tested from master anymore. It could break app.logman. It has to be tested before merging.

2024-03-15 17:16 UTC, ateska commented
@PremyslCerny ?

2024-03-15 17:54 UTC, PremyslCerny commented
It is deployed in nginx in Prima and Composite. If you want me to test it with Maestro, you need to show me how to do it properly, maybe on some WS.

2024-03-17 20:17 UTC, ateska approved these changes

2024-03-27 10:42 UTC, merged