WIP: Fix limited request header to make admin role possible
TeskaLabs/asab-maestro-library pull request #73
Opened 2024-03-05 20:06 UTC by eliska-n

Users with "admin" role in LMIO could not get through nginx (with 500) and Robin found that the list of the resources is so big for admins that it does not fit into headers.

I did this hotfix in app.logman.io but now we need to find some proper place for this bit.

```
2024/03/05 16:31:11 [error] 36#36: *801 upstream sent too big header while reading response header from upstream, client: 109.81.174.194, server: _, request: "GET /api/seacat-auth/credentials?p=1&i=27 HTTP/2.0", subrequest: "/_oauth2_introspect", upstream: "http://10.17.211.99:8900/nginx/introspect/openidconnect", host: "app.logman.io", referrer: "https://app.logman.io/"
```

2024-03-05 21:30 UTC, ateska approved these changes

2024-03-05 21:31 UTC, ateska commented
I'm fine with this approach but feel free to investigate further (to limit the proxy buffer settings to certain locations).

2024-03-06 00:07 UTC, ateska requested changes

2024-03-06 00:07 UTC, ateska commented on Site/ASAB Maestro/Descriptors/seacat-auth.yaml
> +      - proxy_buffer_size         128k
Add a comment that says WHY this is needed.

2024-03-11 09:22 UTC, eliska-n commented
@ateska please approve, so it can be merged

@byewokko please investigate further, (e.g. whether we could use this config for introspection endpoint only)

2024-03-11 09:23 UTC, eliska-n commented
tested hard way on app.logman.io

2024-03-11 12:09 UTC, byewokko commented
@eliska-n i did some testing on lmiobox and it seems it should be enough to just increase the buffer sizes in the internal introspection locations (`_oauth2_introspect`, `_kibana_introspect` etc.). and the buffers don't even have to be that large.

see this commit for reference: http://gitlab.teskalabs.int/site-config/site-lmio-box/-/commit/4c50bbecb0bd94a2305e5a1ab497a054f86f78ce

2024-03-11 22:17 UTC, ateska approved these changes

2024-03-14 19:41 UTC, merged